### ISSUE TITLE
(JSON-FG) When `time` is missing, hangs on _Checking..._

### ISSUE THREAD

**Issue by jerstlouis** [Geonovum-labs/ogc-checker#98]
Just try removing the "time" line from the default example at https://geonovum-labs.github.io/ogc-checker/?#/json-fg .

Difficult to figure out that is the cause! :)

**Comment by joostfarla** [comment]
@jerstlouis, thanks for reporting! The issue is fixed in https://github.com/Geonovum-labs/ogc-checker/commit/dd9624332ac354224f27bceb0dec72cf0f270a01!

**Comment by jerstlouis** [comment]
Thanks @joostfarla for the fix!
